import '@/app/globals.css';
import type { Metadata } from 'next';
import type { JSX, ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Budget Manager',
  description: 'Generated by Erick',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html className="h-full" lang="en">
      <body className="min-h-screen bg-gradient-to-br from-[#032258] via-[#2a1c33] to-[#18313f] antialiased">
        {children}
      </body>
    </html>
  );
}
